# Site settings
title: Coding and Other Thoughts Blog
header-img: http://www.diaart.org/media/w1050h700/object/hei-north-east-south-west.jpg
email: alexanderbglover@gmail.com
copyright_name: gloverab
description: > # this means to ignore newlines until "baseurl:"
  Future content currently unknown. Let's get there together.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gloverab
learn_profile: gloverab
email_username: alexanderbglover@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
